import { expect, test, type Page } from '@playwright/test'
import { installDatabaseDriver, inspectDatabase, patchRecord } from './auditDatabase.js'

async function makeProject(page: Page): Promise<string> {
  await page.goto('/')
  await expect(page.getByTestId('quick-capture')).toBeVisible()
  await installDatabaseDriver(page)
  await page.getByTestId('project-add').click()
  await page.getByTestId('project-create-input').fill('滑块并发测试')
  await page.getByTestId('project-create-save').click()
  await page.getByTestId('project-row').filter({ hasText: '滑块并发测试' }).click()
  const record = (await inspectDatabase(page)).records.find((row) => row.type === 'project')
  if (!record) throw new Error('未创建测试大事')
  await patchRecord(page, record.id, { serverVersion: 1, syncState: 'synced' }, true)
  return record.id
}

test('R10：同步更新后 Tab 和未改变的 pointerup 不写回旧进度', async ({ page }) => {
  const id = await makeProject(page)
  await patchRecord(page, id, { progress: 75, serverVersion: 2, syncState: 'synced' })
  const slider = page.getByTestId('project-slider')
  await expect(slider).toHaveValue('75')
  await page.getByTestId('project-preset-0').focus()
  await page.keyboard.press('Shift+Tab')
  await expect(slider).toBeFocused()
  await slider.dispatchEvent('pointerup', { pointerId: 1 })
  const after = await inspectDatabase(page)
  expect(after.records.find((row) => row.id === id)?.progress).toBe(75)
  expect(after.outbox.filter((row) => row.recordId === id)).toHaveLength(0)
})

test('R10：连续键盘调整只排一次 mutation', async ({ page }) => {
  const id = await makeProject(page)
  const slider = page.getByTestId('project-slider')
  await slider.focus()
  await page.keyboard.down('ArrowRight')
  await page.keyboard.down('ArrowRight')
  await page.keyboard.down('ArrowRight')
  await page.keyboard.up('ArrowRight')
  await expect(slider).toHaveValue('15')
  const writes = (await inspectDatabase(page)).outbox.filter((row) => row.recordId === id)
  expect(writes).toHaveLength(1)
  expect(writes[0]?.payload.progress).toBe(15)
})

test('R10：拖动取消以及交互期间同步更新不会静默覆盖', async ({ page }) => {
  const id = await makeProject(page)
  const slider = page.getByTestId('project-slider')
  await slider.focus()
  await page.keyboard.down('ArrowRight')
  await expect(slider).toHaveValue('5')
  await slider.dispatchEvent('pointercancel', { pointerId: 1 })
  await page.keyboard.up('ArrowRight')
  await expect(slider).toHaveValue('0')
  expect((await inspectDatabase(page)).outbox.filter((row) => row.recordId === id)).toHaveLength(0)

  await page.keyboard.down('ArrowRight')
  await expect(slider).toHaveValue('5')
  await patchRecord(page, id, { progress: 75, serverVersion: 2, syncState: 'synced' })
  await page.keyboard.up('ArrowRight')
  await expect(slider).toHaveValue('75')
  expect((await inspectDatabase(page)).outbox.filter((row) => row.recordId === id)).toHaveLength(0)
})

test('R10：动作期间同步的新进度保持不变，旧动作须重新调整', async ({ page }) => {
  const id = await makeProject(page)
  const slider = page.getByTestId('project-slider')
  await slider.focus()
  await page.keyboard.down('ArrowRight')
  await expect(slider).toHaveValue('5')
  await patchRecord(page, id, { progress: 75, serverVersion: 2, syncState: 'synced' })
  await page.keyboard.up('ArrowRight')
  await expect(slider).toHaveValue('75')
  expect((await inspectDatabase(page)).outbox.filter((row) => row.recordId === id)).toHaveLength(0)
})

test('R10：调整后退回开始值属于没有实际改动，不覆盖期间到达的新进度', async ({ page }) => {
  const id = await makeProject(page)
  const slider = page.getByTestId('project-slider')
  await slider.focus()
  await page.keyboard.down('ArrowRight')
  await expect(slider).toHaveValue('5')
  await page.keyboard.down('ArrowLeft')
  await expect(slider).toHaveValue('0')
  await patchRecord(page, id, { progress: 75, serverVersion: 2, syncState: 'synced' })
  await page.keyboard.up('ArrowLeft')
  await page.keyboard.up('ArrowRight')
  await expect(slider).toHaveValue('75')
  expect((await inspectDatabase(page)).outbox.filter((row) => row.recordId === id)).toHaveLength(0)
  await expect(page.getByText('进度已更新为 75%', { exact: false })).toHaveCount(0)
})

test('R10：鼠标拖动中不落库，松手后保存一次', async ({ page }) => {
  const id = await makeProject(page)
  const slider = page.getByTestId('project-slider')
  const bounds = await slider.boundingBox()
  if (!bounds) throw new Error('滑块不可见')
  const y = bounds.y + bounds.height / 2
  await page.mouse.move(bounds.x + 2, y)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width * 0.75, y, { steps: 8 })
  const value = Number(await slider.inputValue())
  expect(value).toBeGreaterThan(0)
  expect((await inspectDatabase(page)).outbox.filter((row) => row.recordId === id)).toHaveLength(0)
  await page.mouse.up()
  await expect.poll(async () => (await inspectDatabase(page)).records.find((row) => row.id === id)?.progress).toBe(value)
  const writes = (await inspectDatabase(page)).outbox.filter((row) => row.recordId === id)
  expect(writes).toHaveLength(1)
  expect(writes[0]?.payload.progress).toBe(value)
})
