import { expect, test, type Page } from '@playwright/test'
import { installDatabaseDriver, inspectDatabase, patchRecord } from './auditDatabase.js'

async function makeIdea(page: Page, content: string): Promise<string> {
  await page.goto('/')
  const input = page.getByTestId('quick-capture-input')
  await expect(input).toBeVisible()
  await installDatabaseDriver(page)
  await input.fill(content)
  await page.getByTestId('quick-capture-idea').click()
  await expect(input).toHaveValue('')
  const snapshot = await inspectDatabase(page)
  const record = snapshot.records.find((row) => row.content === content)
  if (!record) throw new Error('未创建测试记录')
  await patchRecord(page, record.id, { serverVersion: 1, syncState: 'synced' }, true)
  await page.getByTestId('timeline').getByTestId('record-row').filter({ hasText: content }).locator('button').click()
  await page.getByTestId('detail-edit').click()
  return record.id
}

test('R09：提示后再次更新，确认草稿也必须重新 CAS', async ({ page }) => {
  const id = await makeIdea(page, '编辑开始时的内容')
  const before = (await inspectDatabase(page)).records.find((row) => row.id === id)
  await page.getByTestId('detail-editor').fill('我的未保存草稿')
  await patchRecord(page, id, { content: '已拉取的第二版', serverVersion: 2, syncState: 'synced' })
  await page.getByTestId('detail-save').click()
  await expect(page.getByTestId('detail-stale-current')).toHaveText('已拉取的第二版')
  await expect(page.getByTestId('detail-editor')).toHaveValue('我的未保存草稿')
  expect((await inspectDatabase(page)).outbox.filter((row) => row.recordId === id)).toHaveLength(0)

  await patchRecord(page, id, { content: '提示期间到达的第三版', serverVersion: 3, syncState: 'synced' })
  await page.getByTestId('detail-stale-keep').click()
  await expect(page.getByTestId('detail-stale-current')).toHaveText('提示期间到达的第三版')
  expect((await inspectDatabase(page)).outbox.filter((row) => row.recordId === id)).toHaveLength(0)

  await page.getByTestId('detail-stale-keep').click()
  await expect(page.getByTestId('detail-content')).toHaveText('我的未保存草稿')
  const after = await inspectDatabase(page)
  const writes = after.outbox.filter((row) => row.recordId === id)
  expect(writes).toHaveLength(1)
  expect(writes[0]?.baseServerVersion).toBe(3)
  expect(writes[0]?.baseSnapshot.content).toBe('提示期间到达的第三版')
  expect(after.records.find((row) => row.id === id)?.createdAtUtc).toBe(before?.createdAtUtc)
})

test('R09：同 serverVersion 的本机更新也不能被旧草稿覆盖，可以载入最新内容', async ({ page }) => {
  const id = await makeIdea(page, '本机原内容')
  await page.getByTestId('detail-editor').fill('旧草稿')
  await patchRecord(page, id, { content: '同版本的另一处本机编辑' })
  await page.getByTestId('detail-save').click()
  await expect(page.getByTestId('detail-stale-current')).toHaveText('同版本的另一处本机编辑')
  await page.getByTestId('detail-stale-reload').click()
  await expect(page.getByTestId('detail-editor')).toHaveValue('同版本的另一处本机编辑')
  await expect(page.getByTestId('detail-stale')).toHaveCount(0)
  expect((await inspectDatabase(page)).outbox.filter((row) => row.recordId === id)).toHaveLength(0)
})

test('R09：详情编辑期间同步软删，草稿保留且不隐式恢复', async ({ page }) => {
  const id = await makeIdea(page, '稍后被软删的记录')
  await page.getByTestId('detail-editor').fill('仍可复制保留的详情草稿')
  const deletedAtUtc = '2026-10-06T01:00:00.000Z'
  await patchRecord(page, id, { deletedAtUtc, serverVersion: 2, syncState: 'synced' })
  await page.getByTestId('detail-save').click()
  await expect(page.getByTestId('detail-editor')).toHaveValue('仍可复制保留的详情草稿')
  await expect(page.getByTestId('detail-editor')).toBeEditable()
  const after = await inspectDatabase(page)
  expect(after.records.find((row) => row.id === id)?.deletedAtUtc).toBe(deletedAtUtc)
  expect(after.outbox.filter((row) => row.recordId === id)).toHaveLength(0)
})

test('R09：进展编辑也保留旧草稿并确认最新快照', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('quick-capture')).toBeVisible()
  await installDatabaseDriver(page)
  await page.getByTestId('project-add').click()
  await page.getByTestId('project-create-input').fill('进展 CAS 的大事')
  await page.getByTestId('project-create-save').click()
  await page.getByTestId('project-row').filter({ hasText: '进展 CAS 的大事' }).click()
  await page.getByTestId('project-log-input').fill('进展原内容')
  await page.getByTestId('project-log-save').click()
  const log = (await inspectDatabase(page)).records.find((row) => row.type === 'log' && row.content === '进展原内容')
  if (!log) throw new Error('未创建测试进展')
  await patchRecord(page, log.id, { serverVersion: 1, syncState: 'synced' }, true)
  await page.getByTestId('project-log-row').filter({ hasText: '进展原内容' }).click()
  await page.getByTestId('project-log-editor-input').fill('进展草稿')
  await patchRecord(page, log.id, { content: '另一处的进展更新', serverVersion: 2, syncState: 'synced' })
  await page.getByTestId('project-log-editor-save').click()
  await expect(page.getByTestId('project-log-stale-current')).toHaveText('另一处的进展更新')
  await expect(page.getByTestId('project-log-editor-input')).toHaveValue('进展草稿')
  await page.getByTestId('project-log-stale-keep').click()
  await expect(page.getByTestId('project-log-row')).toContainText('进展草稿')
  const after = await inspectDatabase(page)
  expect(after.records.find((row) => row.id === log.id)?.parentId).toBe(log.parentId)
  expect(after.records.find((row) => row.id === log.id)?.createdAtUtc).toBe(log.createdAtUtc)
  expect(after.outbox.filter((row) => row.recordId === log.id)).toHaveLength(1)
})

test('R09：同步软删正在编辑的进展，取消前不能卸载草稿', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('quick-capture')).toBeVisible()
  await installDatabaseDriver(page)
  await page.getByTestId('project-add').click()
  await page.getByTestId('project-create-input').fill('保护软删进展草稿的大事')
  await page.getByTestId('project-create-save').click()
  await page.getByTestId('project-row').filter({ hasText: '保护软删进展草稿的大事' }).click()
  await page.getByTestId('project-log-input').fill('即将被远端软删的进展')
  await page.getByTestId('project-log-save').click()
  const log = (await inspectDatabase(page)).records.find((row) => row.type === 'log')
  if (!log) throw new Error('未创建测试进展')
  await patchRecord(page, log.id, { serverVersion: 1, syncState: 'synced' }, true)
  await page.getByTestId('project-log-row').click()
  await page.getByTestId('project-log-editor-input').fill('不能因卸载而丢失的进展草稿')
  const deletedAtUtc = '2026-10-06T02:00:00.000Z'
  await patchRecord(page, log.id, { deletedAtUtc, serverVersion: 2, syncState: 'synced' })
  await expect(page.getByTestId('project-log-editor-input')).toHaveValue('不能因卸载而丢失的进展草稿')
  await page.getByTestId('project-log-editor-save').click()
  await expect(page.getByTestId('project-log-editor-input')).toHaveValue('不能因卸载而丢失的进展草稿')
  await expect(page.getByTestId('project-log-editor-input')).toBeEditable()
  let after = await inspectDatabase(page)
  expect(after.records.find((row) => row.id === log.id)?.deletedAtUtc).toBe(deletedAtUtc)
  expect(after.outbox.filter((row) => row.recordId === log.id)).toHaveLength(0)
  await page.getByTestId('project-log-editor-cancel').click()
  await expect(page.getByTestId('project-log-editor')).toHaveCount(0)
  await expect(page.getByTestId('project-log-row')).toHaveCount(0)
  after = await inspectDatabase(page)
  expect(after.records.find((row) => row.id === log.id)?.deletedAtUtc).toBe(deletedAtUtc)
})
